language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t remarkablejames/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true remarkablejames/frontend-docker npm run test
